### PR TITLE
[replicated-library] Add additional information on updating the READE files

### PR DESCRIPTION
**Pull request by chris-sanders**

### CODE REVIEW

**Comment by diamonwiggins** [comment]
Any reason we're deleting the values section?

**Review by xavpaice — APPROVED** [review]
LGTM, need someone who knows the process to review also

**Comment by chris-sanders** [comment]
@diamonwiggins ah right, I forgot I did that. I adjusted a couple of sections but removing the values was the largest and the reason behind is that it's basically unreadable. The values-example.yaml seems like the only reasonable way for people to read it. I also removed the empty dependencies section since it was an empty table.

I did however mean to add a link to values-example under usage along with the link to the example chart. I've added that now.

**Comment by diamonwiggins** [comment]
> @diamonwiggins ah right, I forgot I did that. I adjusted a couple of sections but removing the values was the largest and the reason behind is that it's basically unreadable. The values-example.yaml seems like the only reasonable way for people to read it. I also removed the empty dependencies section since it was an empty table.
> 
> I did however mean to add a link to values-example under usage along with the link to the example chart. I've added that now.

Gotcha, i do like the values table, but agree it isn't very readable at the moment due to it's formatting. I think in the future we could get it formatted better so it looks a bit more like https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common#values and re-add it.

**Review by diamonwiggins — APPROVED** [review]

**Comment by chris-sanders** [comment]
Yea if it's readable that wouldn't bother me at all. I feel like as we continue to add Troubleshoot templates and expand our coverage of the K8s API this list is going to get crazy, but that link does look better.

**Pull request merged**
