### PR TITLE
Unit Tests with Terratest

### PR DESCRIPTION
**Pull request by diamonwiggins**
**Overview**:

Restructuring the initial test from the original proposal in #101 to be similar to how we do them in other projects like troubleshoot.

* Uses a struct for each test case
* Uses the mock k8s client for working with objects rendered by the helm chart to avoid needing to iterate through a multidoc

**Open questions**:

* Does this format make sense? Is checking the amount of containers created across one or more apps, a test that we'd actually write?
* Does using the K8s mock client make sense? If feels that it would be a bit easier for someone getting started with this project to work with the objects via the mock k8s client as opposed to iterating through a multidoc as the original PR is doing - https://github.com/replicatedhq/helm-charts/pull/101/files#diff-9498beb1af424f7771e413e43a0dc03e16dc452f267a9e8345127a5f6ebe840eR49

**Notes**:

Having to hardcode GVKs in the switch statement in the `k8sApply` function isn't ideal, but i'm not sure we would have ever gotten around needing to marshal each GVK that we need for a particular test. I tried digging around to see if there was a way to essentially mock a `kubectl apply` with the fake kubernetes client, but didn't have much luck and didn't want to burn too much time on it. See - https://ymmt2005.hatenablog.com/entry/2020/04/14/An_example_of_using_dynamic_client_of_k8s.io/client-go

**Next steps**:
* If this a direction we want to continue with, I can add some additional coverage over a few other things and then get another review

### CODE REVIEW

**Comment by xavpaice** [comment]
I think this direction is pretty clear for a Go dev to work with,  and if the fake client is enough to determine what the output looks like then it seems like a pretty solid way to go.  Future work would be e2e tests using c17x for a 'real' k8s, but that's not the intent here.

I'd like to see where this goes with some more varied test cases, and also how we go about adding it to Github workflows.

**Comment by DexterYan** [comment]
I think this format is quite good. For the fake client, I am think if it is possible to use the client from https://github.com/kubernetes-sigs/e2e-framework. Then may mock a kubectl apply easily.

**Comment by chris-sanders** [comment]
Oh that's neat, so the fake client with a switch statement utility sets up a fake cluster and then you can just list and query for the items you want. That's looking pretty good. The next things, similer to what Xav said above, that I think it would be nice to explore are.

* Verify the images on these deployments rather that just the count. Just curious to see how selecting the 'right' deployment looks as I suspect thats more typical.
* Verify nothing unexpected exists.

I'm curious once you're working with a client rather than the files, how might someone verify "I didn't create something I don't want". Seems easier to do with the document b/c you have a list to search and verify, with the fake cluster that might be harder?

**Comment by diamonwiggins** [comment]
> I'm curious once you're working with a client rather than the files, how might someone verify "I didn't create something I don't want". Seems easier to do with the document b/c you have a list to search and verify, with the fake cluster that might be harder?

Are you saying in the event that you're creating 3 objects with the library chart say a configmap, secret, and app to ensure that your end result is 3 objects as well? If so, then yeah I think being able to iterate over a doc would probably be a little straightforward vs. using `client-go`. I think you could still get the fake client to work, but maybe that's a test case where you still iterate over the document, but in most other scenarios it makes sense to use `client-go`?

Also depends how strict that test would be i suppose. Checking there are 3 objects is one thing, but ensuring the 3 objects that were created are exactly what you wanted would still require you do the type checking/unmarshaling where `client-go` is a bit cleaner.

**Comment by diamonwiggins** [comment]
> I think this format is quite good. For the fake client, I am think if it is possible to use the client from https://github.com/kubernetes-sigs/e2e-framework. Then may mock a kubectl apply easily.

Nice. I'm not too familiar with this, but perhaps we can create a story for this one to evaluate getting rid of the `switch` statement I have. That'd be awesome.

**Comment by chris-sanders** [comment]
> Are you saying in the event that you're creating 3 objects with the library chart say a configmap, secret, and app to ensure that your end result is 3 objects as well? If so, then yeah I think being able to iterate over a doc would probably be a little straightforward vs. using client-go. I think you could still get the fake client to work, but maybe that's a test case where you still iterate over the document, but in most other scenarios it makes sense to use client-go?

> Also depends how strict that test would be i suppose. Checking there are 3 objects is one thing, but ensuring the 3 objects that were created are exactly what you wanted would still require you do the type checking/unmarshaling where client-go is a bit cleaner.

I was thinking about the `existingClaim` setting on persistence. But when I put it into a specific examples like that, I guess you could just list volume claims and verify none were created. So that's actually not a problem with the client either.

**Comment by diamonwiggins** [comment]
This still needs some more thought. This format starts to get really slow the more test cases you add because for each set of values passed, i'm rendering the chart each time which is noticeably slow. It's probably going to be better to structure this a little more closely to the original PR in the sense that each test "function" will test multiple things.

So instead of there being a function like `TestDeployment_ExpectedNumOfContainers`, I think it's going to have to be `TestDeployment`, `TestStatefulSet`, `TestAppWithService`, so each function will be a bit more generic and will have a bunch of different test cases in it vs. it being a bit more modular how we're used to. Still noodling on this.

**Comment by diamonwiggins** [comment]
Latest commit includes a new "monolith" function that we would continuously add cases to. Haven't thought of anything clever to keep the format of the `TestDeployment_ExpectedNumOfContainers` function that wouldn't require rendering the template for each test cases.

**Comment by diamonwiggins** [comment]
I've removed the parallelism from the test runs as when the chart is being rendered it uses a `tmpcharts` directory and there's intermittently collisions in one test cleaning up this directory while another is trying to use it.

**Comment by danj-replicated** [comment]
> I've removed the parallelism from the test runs as when the chart is being rendered it uses a `tmpcharts` directory and there's intermittently collisions in one test cleaning up this directory while another is trying to use it.

is that set from `testChartPath, err := filepath.Abs("../charts/test")` ?  
could we not use [os.tmpDir](https://pkg.go.dev/os#TempDir) to avoid that?

**Review by danj-replicated — APPROVED** [review]
I think this is a solid start. lgtm

**Pull request merged**
