### PR TITLE
update Troubleshoot templates for a default namespace

### PR DESCRIPTION
**Pull request by xavpaice**
Several collectors need to have a namespace specified, or they will either fail or attempt to collect from all namespaces.  A sensible default for Helm based installs is to collect from the chart namespace, unless told othewise.

### CODE REVIEW

**Review by chris-sanders — COMMENTED** [review]
I like the change, and it looks like it works can you tell us what you tested it against? Until we have testing, we're just posting what chart or change we tested it against.

**Comment by DexterYan** [comment]
I think it is more reasonable. 

Also, since our secretName and configMapName are not limited only to our charts, I changed some example and comments for the namespace part

**Comment by xavpaice** [comment]
I've tested this version against the wg-easy chart, substituting namespaces and leaving them out entirely.

Will need a version bump when we come to it.

**Review by chris-sanders — APPROVED** [review]
We still don't have tests, but I think this is a good change.

**Pull request merged**
