### PR TITLE
Fix multi container probe rendering

### PR DESCRIPTION
**Pull request by diamonwiggins**
When an app has multiple containers that specify Readiness or Liveness probes, the values of one container's probes were being appended to the next.

This PR uses `deepCopy` to enforce the expected behavior that only the result of the merge is returned as opposed to the underlying variable being modified as well.

Before:

values.yaml
```
    containers:
      some-container:
      ...
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
      another-container:
      ...
        livenessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - pidof node
```

rendered
```
        - name: another-contianer
          ....
          livenessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - pidof node
            failureThreshold: 5
            initialDelaySeconds: 0
            periodSeconds: 10
            successThreshold: 1
            terminationGracePeriodSeconds: 30
            timeoutSeconds: 5
            httpGet:
              path: /healthz
              port: http
```

With these changes the templated is rendered correctly:
rendered
```
        - name: another-container
          ....
          livenessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - pidof node
            failureThreshold: 5
            initialDelaySeconds: 0
            periodSeconds: 10
            successThreshold: 1
            terminationGracePeriodSeconds: 30
            timeoutSeconds: 5
```

### CODE REVIEW

**Comment by diamonwiggins** [comment]
See - https://github.com/newrelic/helm-charts/issues/858. It's good to be aware of the fact that helm variables are passed by reference. My initial fix was to try and create a separate variable to use in which I just `{{- $probes := $.Values.defaults....}}`, but to my confusion that didn't work until i read the above issue.

**Review by adamancini — APPROVED** [review]
lgtm

**Review by chris-sanders — CHANGES_REQUESTED** [review]
Ah deep copy, good catch. Unless this is extremely critical let's get a test in before we land it.

**Review by chris-sanders — APPROVED** [review]
lgtm

**Pull request merged**
